-- MySQL Script generated by MySQL Workbench
-- Sun Nov  9 19:49:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pollution_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pollution_db` ;

-- -----------------------------------------------------
-- Schema pollution_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pollution_db` DEFAULT CHARACTER SET utf8 ;
USE `pollution_db` ;

-- -----------------------------------------------------
-- Table `pollution_db`.`constituency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pollution_db`.`constituency` ;

CREATE TABLE IF NOT EXISTS `pollution_db`.`constituency` (
  `constituency_id` INT NOT NULL AUTO_INCREMENT,
  `constituency_name` VARCHAR(50) NOT NULL,
  `mp_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`constituency_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pollution_db`.`station`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pollution_db`.`station` ;

CREATE TABLE IF NOT EXISTS `pollution_db`.`station` (
  `site_id` INT NOT NULL AUTO_INCREMENT,
  `station_name` VARCHAR(50) NOT NULL,
  `latitude` DECIMAL(10,6) NOT NULL,
  `longitude` DECIMAL(10,6) NOT NULL,
  `constituency_id` INT NOT NULL,
  PRIMARY KEY (`site_id`),
  CONSTRAINT `fk_station_constituency`
    FOREIGN KEY (`constituency_id`)
    REFERENCES `pollution_db`.`constituency` (`constituency_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_station_constituency_idx` ON `pollution_db`.`station` (`constituency_id` ASC);


-- -----------------------------------------------------
-- Table `pollution_db`.`reading`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pollution_db`.`reading` ;

CREATE TABLE IF NOT EXISTS `pollution_db`.`reading` (
  `reading_id` INT NOT NULL AUTO_INCREMENT,
  `date_time` DATETIME NOT NULL,
  `nox` FLOAT NULL,
  `no2` FLOAT NULL,
  `no` FLOAT NULL,
  `pm10` FLOAT NULL,
  `pm2_5` FLOAT NULL,
  `o3` FLOAT NULL,
  `co` FLOAT NULL,
  `so2` FLOAT NULL,
  `vpm10` FLOAT NULL,
  `nvpm2_5` FLOAT NULL,
  `vpm2_5` FLOAT NULL,
  `nvpm10` FLOAT NULL,
  `temperature` FLOAT NULL,
  `pressure` FLOAT NULL,
  `rh` FLOAT NULL,
  `objectid` INT NULL,
  `objectid2` INT NULL,
  `site_id` INT NOT NULL,
  PRIMARY KEY (`reading_id`),
  CONSTRAINT `fk_reading_station1`
    FOREIGN KEY (`site_id`)
    REFERENCES `pollution_db`.`station` (`site_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_reading_station1_idx` ON `pollution_db`.`reading` (`site_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
